source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'Coorpacademy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for the app
end
