install! 'cocoapods', :deterministic_uuids => false

platform :ios, '9.0'

target 'Coorpacademy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => rn_path, :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    'RCTImage', # Needed for react-native-svg
    'RCTLinkingIOS', # Needed for react-navigation
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => "#{rn_path}/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs"

  # Firebase
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/DynamicLinks', '~> 5.20.1'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  # Tracking
  pod 'GoogleTagManager'

  # Pods for the app
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'
  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'
  pod 'react-native-video', :path => '../node_modules/react-native-video'
  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  # Lottie
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
end

# The following is needed to ensure the "archive" step works in XCode.
# It removes React from the Pods project, as it is already included in the main project.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
