# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.122.0"

default_platform :ios

platform :ios do
  before_all do |lane|
    ENV["XCODEPROJ"] = "Coorpacademy.xcodeproj"
    ENV["PLIST_PATH"] = "Coorpacademy/Info.plist"
    ENV["CURRENT_USER"] = `whoami`.chomp

    if "#{lane}" == "adhoc"
      ENV["REACT_NATIVE_BUILD_TYPE"] = "adhoc"
    elsif "#{lane}" == "beta"
      ENV["REACT_NATIVE_BUILD_TYPE"] = "distribution"
    end

    puts "Build type: #{ENV["REACT_NATIVE_BUILD_TYPE"]}"

    skip_docs
    setup_circle_ci
    yarn(step_name: 'xcode_check', command: 'xcode:check', project_root: '..')
    yarn(step_name: 'update_version', command: 'update:version', project_root: '..')
    yarn(step_name: 'generate_ios_bundle', command: 'generate:bundle:ios', project_root: '..')
  end

  lane :version do
    fetch_version_code platform: :ios
    puts ENV['VERSION_CODE']
  end

  desc "build an adhoc release for internal store"
  lane :adhoc do
    match(type: "adhoc", readonly: true)
    pem(
      team_id: ENV["TEAM_ID"],
      app_identifier: ENV["APP_IDENTIFIER"]
    )
    update_app_identifier(
      app_identifier: ENV["APP_IDENTIFIER"],
      xcodeproj: ENV["XCODEPROJ"],
      plist_path: ENV["PLIST_PATH"]
    )
    update_project_provisioning(
      xcodeproj: ENV["XCODEPROJ"],
      build_configuration: "Adhoc",
      profile: ENV["sigh_com.coorpacademy.app_adhoc_profile-path"]
    )
    update_info_plist(
      plist_path: ENV["PLIST_PATH"],
      display_name: ENV["DISPLAY_NAME"]
    )
    update_project_team
    gym(
      export_method: 'ad-hoc',
      configuration: 'Adhoc'
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    version_code = fetch_version_code(
      endpoint: "api.coorpacademy.com/mobile/api/v1/build-number/#{:ios}/increment",
      method: :post,
      secret_header: 'Api-Secret',
      secret_value: ENV['VERSION_API_SECRET']
    )
    increment_build_number(build_number: version_code)
    match(type: "appstore", readonly: true)
    pem(
      team_id: ENV["TEAM_ID"],
      app_identifier: ENV["APP_IDENTIFIER"]
    )
    update_app_identifier(
      app_identifier: ENV["APP_IDENTIFIER"],
      xcodeproj: ENV["XCODEPROJ"],
      plist_path: ENV["PLIST_PATH"]
    )
    update_project_provisioning(
      xcodeproj: ENV["xcodeproj"],
      build_configuration: "Release",
      profile: ENV["sigh_com.coorpacademy.app_appstore_profile-path"]
    )
    update_info_plist(
      plist_path: ENV["PLIST_PATH"],
      display_name: ENV["DISPLAY_NAME"]
    )
    update_project_team
    gym
    testflight(
      team_id: ENV["ITC_TEAM_ID"],
      app_identifier: ENV["APP_IDENTIFIER"],
      skip_waiting_for_build_processing: true
    )
    yarn(
      step_name: "notify_publication",
      command: "notify:publication",
      options: [
        ":iphone: Build number *#{version_code}* should be available in the store soon :rocket:",
        "good",
        "Publication of Ios App Successful"
      ],
      project_root: '..'
    )
  end
end
