// @flow
// THIS FILE IS AUTOGENERATED
/* eslint-disable import/max-dependencies */
require('./components/box.stories.js');
require('./components/brand-theme-provider.stories.js');
require('./components/button.stories.js');
require('./components/card-correction.stories.js');
require('./components/card.stories.js');
require('./components/cards.stories.js');
require('./components/correction.stories.js');
require('./components/gradient.stories.js');
require('./components/header-back-image.stories.js');
require('./components/header-slide-right.stories.js');
require('./components/header-slide.stories.js');
require('./components/image.stories.js');
require('./components/level-end.stories.js');
require('./components/lives.stories.js');
require('./components/preview.stories.js');
require('./components/progression-bar.stories.js');
require('./components/progression.stories.js');
require('./components/question-choice.stories.js');
require('./components/question-choices.stories.js');
require('./components/question.stories.js');
require('./components/resource-overlay.stories.js');
require('./components/screen.stories.js');
require('./components/space.stories.js');
require('./components/text.stories.js');
require('./components/video.stories.js');
